### ISSUE TITLE
SSDP Notworking in AP Mode

### ISSUE THREAD

**Issue by NarinLab** [luc-github/ESP32SSDP#2]
Hi, thankyou for the nice lib

I have a problem with this library when using WiFi in the mode of Access Point. When in WiFi Client or STA mode everything is OK. I don't know if this library can support working in AP mode or not?

Thankyou for the help.

By the way, ,i found this peace of code in the library file:

```IPAddress SSDPClass::localIP(){
    tcpip_adapter_ip_info_t ip;
    if (WiFi.getMode() == WIFI_STA) {
        if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip)) {
            return IPAddress();
        }
    } else if (WiFi.getMode() == WIFI_OFF) {
        if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_ETH, &ip)) {
            return IPAddress();
        }
    }
    return IPAddress(ip.ip.addr);
}

**Comment by luc-github** [comment]
Yes did not use it in AP mode because using captive portal you can access so discovery lib is not really useful. AP support could be added but not sure it make sense.
