### ISSUE TITLE
[BUG] Prevent std::bad_alloc when udp.parsePacket() is called

### ISSUE THREAD

**Issue by wladwnt** [luc-github/ESP32SSDP#26]
When SSDP library is used on ESP32 with other software that consumes lots of RAM, then it might happen that WiFiudp library tries to allocate 1460 Bytes using new operator (in parsePacket() function), but it throws an error (std::bad_alloc), that lead to reboot of ESP32. The reboot can be prevented if in ESP32SSDP.cpp the line number 322:
```c++
nbBytes= _server->parsePacket();
```
replaced by:
```c++
try {nbBytes= _server->parsePacket();} catch (const std::bad_alloc&) { return;}
```

**Comment by luc-github** [comment]
a try / catch should be used  only if no other solution, there should be another solution if allocation of new failed

**Comment by wladwnt** [comment]
Why not, this is most simple and efficient way and the only way without changing WiFiudp lib. It does not harm anything. SSDP will still continue working (when next udp packet arrived)

**Comment by luc-github** [comment]
I  see there is one `new` that is not checked https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiUdp.cpp#L225
Do you think i could be the root cause?

**Comment by wladwnt** [comment]
My traces indicates that it happens rather on line 210: if new operator fails it throws std::bad_alloc.

**Comment by luc-github** [comment]
interresting, line 210 if new fail , it should return null and so function should return 0 
what esp32 core version  do you use?

**Comment by wladwnt** [comment]
I use esp32 arduino 1.0.6 (based in idf 3.3). In my understanding if new operator is used with standart type, then std::bad_alloc is thrown already during new operator execution, so the program aborts before the return value is checked to be zero or not. So lines 2111-213 do not make sense. They would make sense if new would be used like:
```c++
char * buf = new (std::nothrow) char[1460];
```
But might be I am wrong, I am not that deep in this stuff..

**Comment by luc-github** [comment]
Hmm 1.0.6 is known to have several issues actually - I would suggest to try to revert to 1.0.4 or to move to 2.0.0 to see if it can be reproduced.
I never got such issue, but I also never used the 1.0.6 as I have sticked to 1.0.4 for a while,  Now moved to 2.0.0

**Comment by wladwnt** [comment]
In my experience 1.0.6 (idf 3.3.5 based) is much better than 1.0.4 (idf 3.2 based), but must be used correctly.
I tried 2.0.0, it does not work for me now (I use lots of different protocolls, some from esp-idf directly and have to rewrite some parts to be used with esp-idf 4.4 that is basis for esp32-arduino 2.0.0).

I think 99% of arduino users dont have esp32 programms that periodically use almost all of RAM, therefore no one faced this problem with UDP.cpp / new  operator.

**Comment by luc-github** [comment]
any `new` that failed would raise the error, I do not think it is limited to udp

**Comment by wladwnt** [comment]
For sure not, but everything else I use either use malloc() (like AsyncUDP) or (std::nothrow) to handle that cases correctly.
Especially with FreeRTOS it is completly wrong not to handle this case and let bad_alloc exception to be thrown, since just simple solution using vTaskDelay and then retry allocation will do the job in most cases.

Thats why using (actually bad written) Udp lib it is ok, in my opinion, to cath this exception on higher level (=much better than not to do that).

**Comment by luc-github** [comment]
ok so your suggestion is to use try/catch  for now,, then rewrite the lib to use asyncUdp for reliability and so lib will become async
right?

**Comment by wladwnt** [comment]
Danke!
