### ISSUE TITLE
'tcpip_adapter_ip_info_t' was not declared in this scope

### ISSUE THREAD

**Issue by 3dle** [luc-github/ESP32SSDP#3]
IPAddress SSDPClass::localIP(){
    tcpip_adapter_ip_info_t ip;
    if (WiFi.getMode() == WIFI_STA) {
        if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip)) {
            return IPAddress();
        }
    } else if (WiFi.getMode() == WIFI_OFF) {
        if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_ETH, &ip)) {
            return IPAddress();
        }
    }
    return IPAddress(ip.ip.addr);
}

**Comment by luc-github** [comment]
doing what?

**Comment by AKTanara** [comment]
Running Examples for ESP32 (Core version 3.3.2) get same error...

**Comment by michaelheiml** [comment]
I am getting the same Error for ESP32 3.3.5
Everything up to date

**Comment by luc-github** [comment]
it is working for 3.0.4, after arduino-esp32 changed idf version which break again the code - I did not had time to follow the new changes
