### ISSUE TITLE
Deprecated schema()

### ISSUE THREAD

**Issue by Andreotti100** [luc-github/ESP32SSDP#31]
SSDP.schema() is deprecated but still used in your samples,
Can you please update the sample code with SSDP.getSchema() because I can not get it working this way.

**Comment by luc-github** [comment]
it is put deprecated to advice people it will be removed soon but it is still working, it is just a warning

the next version will only  `const char * getSchema();`  which is already implemented - I did not update sample because it is still ok and did not have time for it now

**Comment by Andreotti100** [comment]
I understand.

Your code is working, Thanks buddy!
