### ISSUE TITLE
Duplicate Global Scope Enumerations Prevent Compilation

### ISSUE THREAD

**Issue by Daedelos** [luc-github/ESP32SSDP#40]
**Describe the bug**
Duplicate global scope enumerations in libraries (or own code) provent compilation.

ESP32SSDP.h has a global scope enumeration at line 51 -

typedef enum {
    NONE,
    SEARCH,
    NOTIFY
} ssdp_method_t;

The global scope enumeration elements (NONE, SEARCH, NOTIFY) will conflict with amy other variables or other enums and prevent compilation.

In my case this was another library ezTime.

ezTime.h enum at line 69 -

typedef enum {
	NONE, 
	ERROR,
	INFO,
	DEBUG
} ezDebugLevel_t;

error: 'NONE' conflicts with a previous declaration is raised by the compiler

Moving the ESP32SSDP ssdp_method_t typedef to within the SSDPClass class resolves this conflict.

class SSDPClass
{

typedef enum {
    NONE,
    SEARCH,
    NOTIFY
} ssdp_method_t;

public:
    SSDPClass();

I will raise a similar comment with regard to global enums in the ezTime GitHub repository.

**To Reproduce**
Attempt compilation using:

#include <ezTime.h>
#include <ESP32SSDP.h>

**Expected behavior**
Successful compilation with local scoped enums 

**Firmware:**
- ESP core version: 2.0.15
- Library Version: 1.2.1 async
- Wifi mode: STA  

**Board used (please complete the following information):**
 - MCU: ESP32 
 - Name: DOIT ESP32 DEVKIT V1

**Comment by luc-github** [comment]
ssdp_method_t moved to private
