### ISSUE TITLE
[FEATURE REQUEST] Need ability to change SERVER product name and version in packet.

### ISSUE THREAD

**Issue by f34rdotcom** [luc-github/ESP32SSDP#6]
From the spec for the SERVER product token RFC docs.
  "Server implementors are encouraged to make this field a configurable option."

It is partially a security issue but it also allows me to more clearly identify the service.
https://www.w3.org/Protocols/HTTP/1.1/rfc2616bis/draft-lafon-rfc2616bis-03.html#rfc.section.14.38

**Comment by luc-github** [comment]
this part is in web server not in SSDP from what I understand , or I misunderstand `protocol HTTP`?

**Comment by f34rdotcom** [comment]
Ya, it is all a blur what is what with SSDP :) on its own its just UDP discovery but the headers are rfc HTTP headers. https://github.com/luc-github/ESP32SSDP/blob/4ac65d895986e73389e801a0fe20e6db3f8dc556/ESP32SSDP.cpp#L55

When I implement the HTTP(S) server code it would report similar SERVER header at least for the software and version.

**Comment by luc-github** [comment]
ok can be added for packet nb then

**Comment by luc-github** [comment]
void setServerName(const char *name); function will be added, name string will cover name and version, default will be "Arduino/1.0" if not set

**Comment by luc-github** [comment]
done in https://github.com/luc-github/ESP32SSDP/commit/0c30711d751e0c5ef1d2d7de4230016450de4358

**Comment by f34rdotcom** [comment]
Looks good. Tested.
